
name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies in server
      - name: Install server dependencies
        run: |
          cd server
          npm install

      # Install dependencies in client
      - name: Install client dependencies
        run: |
          cd client
          npm install

      # Run linting in server (Optional: Add ESLint or Prettier)
      - name: Run lint in server
        run: |
          cd server
          npm run lint

      # Run linting in client (Optional: Add ESLint or Prettier)
      - name: Run lint in client
        run: |
          cd client
          npm run lint

      # Run tests in server
      - name: Run tests in server
        run: |
          cd server
          npm test

      # Run tests in client
      - name: Run tests in client
        run: |
          cd client
          npm test

      # Build the application in server
      - name: Build server application
        run: |
          cd server
          npm run build

      # Build the application in client
      - name: Build client application
        run: |
          cd client
          npm run build
