
name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting (Optional: Add ESLint or Prettier)
      - name: Run lint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test

      # Build the application
      - name: Build application
        run: npm run build
